name: pics_uploder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.1
  shared_preferences: ^2.0.13  # Add this line

  oauth2: ^2.0.2
  path_provider: ^2.1.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
